# -*- coding: utf-8 -*-
"""mapa_Rulkov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ywhkR1heEqkWS_ccKt9YpbtrpXHkY29
"""

import numpy as np 
import matplotlib.pyplot as plt
 


def rulkov_map(x0, y0, alpha, sigma,  rho, eps , b): 

  x1 = (alpha  / (1 + (x0 ** 2))) + y0
  y1 = y0 - sigma * (x0 - rho)
  return x1, y1

# number of iterations and array initialization
def orbit(x0, y0, alpha, sigma,  rho, eps , b,  maxiter ):

  X = np.zeros(maxiter+1)
  Y = np.zeros(maxiter+1)

  #start points
  X[0] = x0
  Y[0] = y0

  
  
  # add points to array
  for n in range (maxiter):
    x1, y1 = rulkov_map(X[n], Y[n], alpha, sigma, rho, eps, b)
    X[n+1] = x1
    Y[n+1] = y1
    
    
  return X, Y